apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: test
spec:
  version: v1.29.2-k0s.0
  externalAddress: kmc-test.yoke.clusters.drzzl.io
  kineDataSourceURL: nats://kinats:4222?bucket=kine-test&replicas=2&noEmbed=true
  persistence:
    type: emptyDir
  certificateRefs:
  - type: ca
    name: test-ca-pki
  - type: sa
    name: test-sa-pki
  - type: proxy
    name: test-front-proxy-pki
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: test
    spec:
      telemetry:
        enabled: false
