helmGlobals:
  chartHome: .
helmCharts:
- name: cert-manager
  kubeVersion: "1.29"
  releaseName: main
  valuesInline:
    namespace: certmanager
    installCRDs: true
    enableCertificateOwnerRef: true
