helmGlobals:
  chartHome: .
helmCharts:
- name: cert-manager
  kubeVersion: "1.29"
  releaseName: main
  valuesInline:
    namespace: certmanager
    installCRDs: true
    enableCertificateOwnerRef: true

# Remove instance label so argo doesn't assume multiple apps are controlling these
patches:
- target:
    kind: CustomResourceDefinition
  patch: |- 
    - op: remove
      path: /metadata/labels/app.kubernetes.io~1instance
