resources:
- selfsigned-issuer.yaml

helmGlobals:
  chartHome: .
helmCharts:
- name: v1.14.3
  kubeVersion: "1.29"
  releaseName: main
  valuesInline:
    namespace: certmanager
    installCRDs: true
    enableCertificateOwnerRef: true

# Remove CRD instance label so argo doesn't assume multiple apps are controlling these
patches:
- target:
    kind: CustomResourceDefinition
  patch: |- 
    - op: remove
      path: /metadata/labels/app.kubernetes.io~1instance
