namespace: yoke
resources:
- install.yaml
- workloadidentity.yaml
- kmskey.yaml
- kmspolicy.yaml
- kmsissuer.yaml

images:
- name: ghcr.io/drzzlio/kms-issuer
  newTag: sha-5bde3f6

patches:
- target:
    kind: ServiceAccount
    name: kms-issuer-controller-manager
  patch: |-
    - op: add
      path: /metadata/annotations/iam.gke.io~1gcp-service-account
      value: yoke-kms-issuer@gptops-playground.iam.gserviceaccount.com
- target:
    kind: ClusterRoleBinding
    name: kms-issuer-cert-manager-controller-approve:cert-manager-drzzl-io
  patch: |-
    - op: replace
      path: /subjects/0
      value:
        kind: ServiceAccount
        name: main-cert-manager
        namespace: certmanager
