apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
spec:
  project: default

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  source:
    path: clusters/primary
    repoURL: https://github.com/drzzlio/gitops
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
