apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: gptpolicy-controller.drzzl.io
spec:
  type: Controller
  resources:
  - gptpolicies
  scope: Namespaced
  operations:
  - CREATE
  - DELETE
  javascript: |
    print(`got event ${JSON.stringify(request)}`)
    if(request.operation === 'DELETE') {
      // The first delete with a finalizer has an object
      if(request.object) {
        // TODO: Delete the owned jspolicy instance
      }
    }
