apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: gptpolicy-controller.drzzl.io
spec:
  type: Controller
  resources:
  - gptpolicies
  scope: Namespaced
  operations:
  - CREATE
  - DELETE
  javascript: |
    print(`hi ${request.operation}`)
    if(request.operation === 'DELETE') {
      print(`deleting ${JSON.stringify(request)}`)
    }
