apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: gptpolicy-controller.drzzl.io
spec:
  type: Controller
  resources:
  - gptpolicies
  scope: Namespaced
  operations:
  - CREATE
  - DELETE
  javascript: |
    print(`got event ${JSON.stringify(request)}`)

    if(request.operation === 'DELETE') {
      // The first delete with a finalizer has an object
      if(request.object) {
        // TODO: Delete the owned jspolicy instance
        print(`removing owned jspolicy instance for ${request.name}`)
      }

      // Done with delete handling, jump out
      allow()
    }

    //TODO: Handle creation/update of jspolicy instance
    print(`handling creation of jspolicy for ${request.name}`)

    // Check if the gpt.drzzl.io/genversion annotation matches resourceVersion,
    // if not then we need to create or update the owned jspolicy
    if(request.object.metadata.annotations?.['gpt.drzl.io/genversions'] !== request.object.metadata.resourceVersion) {
      print(`we need to create the jspolicy`)
    }
