apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gptpolicies.gpt.drzzl.io
spec:
  group: gpt.drzzl.io
  scope: Cluster
  names:
    plural: gptpolicies
    singular: gptpolicy
    kind: GPTPolicy
    listKind: GPTPolicyList
    shortNames:
    - gptp
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              description:
                type: string
              existingCode:
                type: string
            required:
            - description
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
