apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: dnsconfig.drzzl.io
spec:
  type: Mutating
  scope: Namespaced
  namespaceSelector:
    matchLabels: 
      kubernetes.io/metadata.name: gptpolicy
  objectSelector:
    matchLabels:
      mx.com/patch-ndots: "true"
  resources:
  - deployments
  operations:
  - CREATE
  - UPDATE
  timeoutSeconds: 30
  javascript: |
    const obj = request.object
    const namespace = obj.metadata.namespace
    const name = obj.metadata.name

    print(`got deployment to patch dns config: ${namespace}.${name}`)

    obj.spec.template.spec.dnsPolicy = 'None';
    obj.spec.template.spec.dnsConfig = {
      options: [
        { name: 'ndots', value: '2' },
      ],
      nameservers: [ '10.68.0.10' ],
      searches: [
        `${namespace}.svc.cluster.local`,
        `svc.cluster.local`,
        `cluster.local`,
      ],
    }
    mutate(obj)

#dnsPolicy: "None"
#dnsConfig:
#  nameservers:
#    - 10.80.80.10
#  searches:
#    - roster.svc.cluster.local
#    - svc.cluster.local
#    - cluster.local
#    - sd.moneydesktop.com
#    - se.moneydesktop.com
#    - moneydesktop.com
#  options:
#    - name: ndots
#      value: "2"
