apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
  name: cloudkms.googleapis.com
spec:
  projectRef:
    external: projects/gptops-playground
