apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  destination:
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
