apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  # FIXME: Don't want to install binaries at runtime! Need kustomize >= 5.3
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
      - name: download-tools
        image: alpine:3.19
        command: [sh, -c]
        args:
        - wget -qO kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz &&
          echo "3ab32f92360d752a2a53e56be073b649abc1e7351b912c0fb32b960d1def854c kustomize.tar.gz" | sha256sum -sc - &&
          tar xvf kustomize.tar.gz &&
          mv kustomize /custom-tools/
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
