apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: kmsissuer-tester-keypolicy
spec:
  resourceRef:
    apiVersion: kms.cnrm.cloud.google.com/v1beta1
    kind: KMSCryptoKey
    name: kmsissuer-test
  bindings:
    - role: roles/cloudkms.signerVerifier
      members:
        - serviceAccount:kmsissuer-tester@gptops-playground.iam.gserviceaccount.com
    - role: roles/cloudkms.viewer
      members:
        - serviceAccount:kmsissuer-tester@gptops-playground.iam.gserviceaccount.com
