apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: kmsissuer-tester
spec:
  displayName: kmsissuer-tester
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: kmsissuer-tester-workloadidentity
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kmsissuer-tester
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        # Gives impersonation permission to actions in the github.com/drzzlio/kms-issuer repo
        - principalSet://iam.googleapis.com/projects/gptops-playground/locations/global/workloadIdentityPools/github/attribute.repository/drzzlio/kms-issuer
