apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-google-cas-issuer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
