apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    path: apps/argocd/overlays/primary

  destination:
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
