apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gptpolicy
spec:
  source:
    path: apps/gptpolicy

  destination:
    namespace: gptpolicy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

