apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
spec:
  source:
    path: apps/httpbin

  destination:
    namespace: httpbin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

