apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jspolicy
spec:
  source:
    path: apps/jspolicy

  destination:
    namespace: jspolicy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

