apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k0smotron
spec:
  source:
    path: apps/k0smotron

  destination:
    namespace: k0smotron

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
