apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drzzlio
spec:
  source:
    path: apps/kmsissuer-test

  destination:
    namespace: ksmissuer-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
