apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: motron
spec:
  source:
    path: apps/jspolicy

  destination:
    namespace: motron

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

