apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yoke
spec:
  source:
    path: apps/yoke/overlays/test

  destination:
    namespace: yoke

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        cnrm.cloud.google.com/project-id: gptops-playground
    syncOptions:
    - CreateNamespace=true
