namespace: jspolicy
helmGlobals:
  chartHome: .
helmCharts:
- name: v0.2.2
  includeCRDs: true
  releaseName: main
  valuesInline:
    serviceAccount:
      name: jspolicy

patches:
- path: deployment.patch.yaml
