apiVersion: v2
description: JavaScript Policies for Kubernetes
home: https://www.jspolicy.com
icon: https://static.loft.sh/jspolicy/logo/jspolicy-logo-black.svg
keywords:
- developer
- development
- sharing
- share
- multi-tenancy
- tenancy
- cluster
- space
- namespace
- vcluster
- vclusters
maintainers:
- email: info@loft.sh
  name: Loft Labs, Inc.
  url: https://twitter.com/loft_sh
name: jspolicy
sources:
- https://github.com/loft-sh/jspolicy
type: application
version: 0.2.2
