name: Run Dyff Between Master and PR Cluster Configs
on:
  pull_request:
    branches: [ master ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
    - run: nix develop --impure -c cdiffreport primary > cdiff.html
    - uses: actions/upload-artifact@v4
      with:
        name: cdiff
        path: cdiff.html
        if-no-files-found: error
        overwrite: true
